import { BasketIcon } from "@sanity/icons";
import { defineArrayMember, defineField, defineType } from "sanity";
import { seedShopPage } from "../seed-data";

const benefitMember = defineArrayMember({
  type: "object",
  name: "benefit",
  fields: [
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    defineField({ name: "body", type: "text", rows: 3, validation: (r) => r.required() }),
  ],
  preview: { select: { title: "title", subtitle: "body" } },
});

const pricingTierMember = defineArrayMember({
  type: "object",
  name: "pricingTier",
  fields: [
    defineField({ name: "tierName", title: "Tier Name", type: "string", validation: (r) => r.required() }),
    defineField({ name: "orderMinimum", title: "Order Minimum", type: "string", validation: (r) => r.required() }),
    defineField({ name: "pricePerCase", title: "Price Per Case", type: "string", validation: (r) => r.required() }),
    defineField({ name: "perks", title: "Perks", type: "string" }),
  ],
  preview: {
    select: { title: "tierName", subtitle: "pricePerCase" },
  },
});

const moqItemMember = defineArrayMember({
  type: "object",
  name: "moqItem",
  fields: [
    defineField({ name: "label", type: "string", validation: (r) => r.required() }),
    defineField({ name: "value", type: "string", validation: (r) => r.required() }),
  ],
  preview: { select: { title: "label", subtitle: "value" } },
});

const stepMember = defineArrayMember({
  type: "object",
  name: "step",
  fields: [
    defineField({ name: "title", type: "string", validation: (r) => r.required() }),
    defineField({ name: "body", type: "text", rows: 2, validation: (r) => r.required() }),
  ],
  preview: { select: { title: "title", subtitle: "body" } },
});

export const shopPage = defineType({
  name: "shopPage",
  title: "Wholesale Page",
  type: "document",
  icon: BasketIcon,
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "catalog", title: "Catalog" },
    { name: "pricing", title: "Pricing & MOQ" },
    { name: "process", title: "How It Works" },
    { name: "quote", title: "Quote Form" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      group: "seo",
      initialValue: seedShopPage.seoTitle,
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 2,
      group: "seo",
      initialValue: seedShopPage.seoDescription,
    }),
    defineField({
      name: "eyebrow",
      title: "Hero Eyebrow",
      type: "string",
      group: "hero",
      initialValue: seedShopPage.eyebrow,
    }),
    defineField({
      name: "title",
      title: "Hero Title",
      type: "string",
      group: "hero",
      initialValue: seedShopPage.title,
      validation: (r) => r.required(),
    }),
    defineField({
      name: "description",
      title: "Hero Description",
      type: "text",
      rows: 4,
      group: "hero",
      initialValue: seedShopPage.description,
    }),
    defineField({
      name: "benefits",
      title: "Benefits",
      type: "array",
      group: "hero",
      initialValue: seedShopPage.benefits,
      of: [benefitMember],
    }),
    defineField({
      name: "catalogEyebrow",
      title: "Catalog Eyebrow",
      type: "string",
      group: "catalog",
      initialValue: seedShopPage.catalogEyebrow,
    }),
    defineField({
      name: "catalogTitle",
      title: "Catalog Title",
      type: "string",
      group: "catalog",
      initialValue: seedShopPage.catalogTitle,
    }),
    defineField({
      name: "catalogDescription",
      title: "Catalog Description",
      type: "text",
      rows: 3,
      group: "catalog",
      initialValue: seedShopPage.catalogDescription,
    }),
    defineField({
      name: "pricingEyebrow",
      title: "Pricing Eyebrow",
      type: "string",
      group: "pricing",
      initialValue: seedShopPage.pricingEyebrow,
    }),
    defineField({
      name: "pricingTitle",
      title: "Pricing Title",
      type: "string",
      group: "pricing",
      initialValue: seedShopPage.pricingTitle,
    }),
    defineField({
      name: "pricingDescription",
      title: "Pricing Description",
      type: "text",
      rows: 3,
      group: "pricing",
      initialValue: seedShopPage.pricingDescription,
    }),
    defineField({
      name: "pricingTiers",
      title: "Pricing Tiers",
      type: "array",
      group: "pricing",
      initialValue: seedShopPage.pricingTiers,
      of: [pricingTierMember],
    }),
    defineField({
      name: "moqEyebrow",
      title: "MOQ Eyebrow",
      type: "string",
      group: "pricing",
      initialValue: seedShopPage.moqEyebrow,
    }),
    defineField({
      name: "moqTitle",
      title: "MOQ Title",
      type: "string",
      group: "pricing",
      initialValue: seedShopPage.moqTitle,
    }),
    defineField({
      name: "moqDescription",
      title: "MOQ Description",
      type: "text",
      rows: 2,
      group: "pricing",
      initialValue: seedShopPage.moqDescription,
    }),
    defineField({
      name: "moqItems",
      title: "MOQ Items",
      type: "array",
      group: "pricing",
      initialValue: seedShopPage.moqItems,
      of: [moqItemMember],
    }),
    defineField({
      name: "howItWorksEyebrow",
      title: "How It Works Eyebrow",
      type: "string",
      group: "process",
      initialValue: seedShopPage.howItWorksEyebrow,
    }),
    defineField({
      name: "howItWorksTitle",
      title: "How It Works Title",
      type: "string",
      group: "process",
      initialValue: seedShopPage.howItWorksTitle,
    }),
    defineField({
      name: "howItWorksSteps",
      title: "Steps",
      type: "array",
      group: "process",
      initialValue: seedShopPage.howItWorksSteps,
      of: [stepMember],
    }),
    defineField({
      name: "quoteEyebrow",
      title: "Quote Section Eyebrow",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.quoteEyebrow,
    }),
    defineField({
      name: "quoteTitle",
      title: "Quote Section Title",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.quoteTitle,
    }),
    defineField({
      name: "quoteDescription",
      title: "Quote Section Description",
      type: "text",
      rows: 3,
      group: "quote",
      initialValue: seedShopPage.quoteDescription,
    }),
    defineField({
      name: "formStoreLabel",
      title: "Form: Store Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formStoreLabel,
    }),
    defineField({
      name: "formContactLabel",
      title: "Form: Contact Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formContactLabel,
    }),
    defineField({
      name: "formEmailLabel",
      title: "Form: Email Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formEmailLabel,
    }),
    defineField({
      name: "formPhoneLabel",
      title: "Form: Phone Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formPhoneLabel,
    }),
    defineField({
      name: "formStoreTypeLabel",
      title: "Form: Store Type Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formStoreTypeLabel,
    }),
    defineField({
      name: "formStoreTypeOptions",
      title: "Form: Store Type Options",
      type: "array",
      of: [{ type: "string" }],
      group: "quote",
      initialValue: seedShopPage.formStoreTypeOptions,
    }),
    defineField({
      name: "formProductsLabel",
      title: "Form: Products Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formProductsLabel,
    }),
    defineField({
      name: "formVolumeLabel",
      title: "Form: Volume Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formVolumeLabel,
    }),
    defineField({
      name: "formRegionLabel",
      title: "Form: Region Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formRegionLabel,
    }),
    defineField({
      name: "formMessageLabel",
      title: "Form: Message Label",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formMessageLabel,
    }),
    defineField({
      name: "formSubmitText",
      title: "Form: Submit Button",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formSubmitText,
    }),
    defineField({
      name: "formSuccessTitle",
      title: "Form: Success Title",
      type: "string",
      group: "quote",
      initialValue: seedShopPage.formSuccessTitle,
    }),
    defineField({
      name: "formSuccessMessage",
      title: "Form: Success Message",
      type: "text",
      rows: 2,
      group: "quote",
      initialValue: seedShopPage.formSuccessMessage,
    }),
  ],
  preview: { prepare: () => ({ title: "Wholesale Page" }) },
});
